version: "3"

networks:
  web:
    external: false
  dashboard:
    external: false

services:
  dashboard-db:
    image: mariadb:11
    restart: unless-stopped
    volumes:
      - ./data-mariadb:/var/lib/mysql:Z
    env_file:
      - ./.envs/.mariadb
    networks:
      - dashboard

  dashboard-app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - ./.envs/.mariadb
      - ./.envs/.app
    networks:
      - dashboard
      - web
    depends_on:
      - dashboard-db
