networks:
  web:
    external: false
  dashboard:
    external: false

services:
  dashboard-db:
    build:
      context: ./dockerfiles/db
      dockerfile: Dockerfile
    restart: unless-stopped
    volumes:
      - ./data-mariadb:/var/lib/mysql:Z
    env_file:
      - ./.envs/.mariadb

    networks:
      - dashboard

  dashboard-app:
    build:
      context: .
      dockerfile: dockerfiles/app/Dockerfile
    restart: unless-stopped
    env_file:
      - ./.envs/.app
      - ./.envs/.mariadb
    networks:
      - dashboard
      - web
    depends_on:
      - dashboard-db
    ports:
      - "8002:80"
